VNDB/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('visualnovels.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visualnovels/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('home/', views.home, name='home'),
    path('visualnovels/detail/<int:vn_id>/', views.visual_novel_detail, name='visual_novel_detail'),
    path('logout/', views.logout, name='logout'),
    path('visualnovels/', views.visual_novels, name='visual_novels'),
    path('companies/', views.company_list, name='company_list'),
    path('companies/detail/<int:company_id>/', views.company_detail, name='company_detail'),
    path('characters/', views.characters, name='characters'),
    path('characters/detail/<int:character_id>/', views.character_detail, name='character_detail'),
    path('genres/', views.genres, name='genres'),
    path('genres/detail/<int:genre_id>/', views.genre_detail, name='genre_detail'),
    path('voice_actors/', views.voice_actors_list, name='voice_actors_list'),
    path('voice_actors/detail/<int:va_id>/', views.voice_actor_detail, name='voice_actor_detail'),
    path('add_visualnovel/', views.add_visualnovel, name='add_visualnovel'),
]

visualnovels/models.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password
# Create your models here.


class Company(models.Model):
    company_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=False, default='No description')
    def __str__(self):
        return self.name
    
    def visualnovel_set(self):
        return self.visualnovel_set.all()

    def get_class_name(self):
        return self.__class__.__name__.lower()

class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    login_name = models.CharField(max_length=200, unique=True)
    email = models.EmailField()
    password = models.CharField(max_length=200)
    special_key = models.IntegerField(null=True)
    description = models.TextField(null=False, default='No description')
    last_login = models.DateTimeField(auto_now=True)

    
    def set_password(self, raw_password):
        self.password = make_password(raw_password)
        
    def check_password(self, raw_password):
        return check_password(raw_password, self.password)
    
    def __str__(self):
        return self.login_name

class VisualNovel(models.Model):
    vn_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    released = models.DateField()
    description = models.TextField(null=False, default='No description')
    image = models.ImageField(upload_to='images/')
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    genres = models.ManyToManyField('Genre', through='VisualNovelGenre')
    status = models.ManyToManyField('User', through='Game_list')
    
    def __str__(self):
        return self.title
    
    def genre_set(self):
        return self.genres.all()
    def company_get(self):
        return self.company.name
    def status_get(self, user: User):
        try:
            game_list = Game_list.objects.get(user_id=user, vn_id=self)
            return game_list.status
        except Game_list.DoesNotExist:
            return None
        
    def get_class_name(self):
        return 'visual_novel'

class Character(models.Model):
    character_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    age = models.IntegerField()
    birth_date = models.DateField()
    description = models.TextField(null=False, default='No description')
    company_id = models.ForeignKey(Company, on_delete=models.DO_NOTHING)
    vn_id = models.ForeignKey(VisualNovel, on_delete=models.DO_NOTHING)
    name: str = first_name.__str__() + " " + last_name.__str__()
    def __str__(self):
        return self.first_name + " " + self.last_name
    
    def get_class_name(self):
        return self.__class__.__name__.lower()

class Genre(models.Model):
    genre_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=False, default='No description')
    
    def __str__(self):
        return self.name
    
    def visualnovel_set(self):
        try:
            visualnovels = VisualNovelGenre.objects.filter(genre_id=self)
            return visualnovels
        except VisualNovelGenre.DoesNotExist:
            return None
    def get_class_name(self):
        return self.__class__.__name__.lower()

class VisualNovelGenre(models.Model):
    vn_id = models.ForeignKey(VisualNovel, on_delete=models.CASCADE, related_name='visualnovelgenre')
    genre_id = models.ForeignKey(Genre, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = (('vn_id', 'genre_id'),)
        
    def __str__(self):
        return f"{self.vn_id.title} - {self.genre_id.name}" 

class Language(models.Model):
    language_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name

class System_language(models.Model):
    language_id = models.ForeignKey(Language, on_delete=models.CASCADE)
    vn_id = models.ForeignKey(VisualNovel, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = (('language_id', 'vn_id'),)

class Voice_language(models.Model):
    language_id = models.ForeignKey(Language, on_delete=models.CASCADE)
    vn_id = models.ForeignKey(VisualNovel, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = (('language_id', 'vn_id'),)

class Nationality(models.Model):
    nationality_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name

class Voice_actor(models.Model):
    va_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    age = models.IntegerField()
    birth_date = models.DateField()
    nationality_id  = models.ForeignKey(Nationality, on_delete=models.DO_NOTHING)
    language_id = models.ForeignKey(Language, on_delete=models.DO_NOTHING)
    name: str = first_name.__str__() + " " + last_name.__str__()
    
    def __str__(self):
        return self.first_name + " " + self.last_name
    
    def get_characters(self):
        try:
            characters = Character_voice_actor.objects.filter(va_id=self)
            return characters
        except Character_voice_actor.DoesNotExist:
            return None
        
    def get_class_name(self):
        return self.__class__.__name__.lower()
    
class Character_voice_actor(models.Model):
    character_id = models.ForeignKey(Character, on_delete=models.CASCADE)
    va_id = models.ForeignKey(Voice_actor, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = (('character_id', 'va_id'),)

class Character_genre(models.Model):
    character_id = models.ForeignKey(Character, on_delete=models.CASCADE)
    genre_id = models.ForeignKey(Genre, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = (('character_id', 'genre_id'),)

class Character_liked(models.Model):
    character_id = models.ForeignKey(Character, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = (('character_id', 'user_id'),)

class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    comment = models.TextField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    vn_id = models.ForeignKey(VisualNovel, on_delete=models.CASCADE)

class Game_list(models.Model):
    status = models.IntegerField(default=0)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    vn_id = models.ForeignKey(VisualNovel, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = (('user_id', 'vn_id'),)

class Rating(models.Model):
    rate = models.IntegerField(default=0)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    vn_id = models.ForeignKey(VisualNovel, on_delete=models.CASCADE)
    
    RATE_CHOICES = (
        (0, '0 - Not rated'),
        (1, '1 - Terrible'),
        (2, '2 - Very bad'),
        (3, '3 - Bad'),
        (4, '4 - Poor'),
        (5, '5 - Average'),
        (6, '6 - Fine'),
        (7, '7 - Good'),
        (8, '8 - Very good'),
        (9, '9 - Great'),
        (10, '10 - Masterpiece'),
    )
    
    def __str__(self):
        return self.rate


visualnovels/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import UserCreationForm, UserLoginForm, GameListForm, RatingForm, CommentForm, VisualNovelForm, SearchForm
from django.contrib.auth import authenticate

from .models import VisualNovel, Character, User, Game_list, Company, Genre, Voice_actor, Rating, Comment
from django.db.models import Count, Avg, Q
# Create your views here.


def index(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['login_name']
            password = form.cleaned_data['password']
            user = authenticate(request, login_name=username, password=password)
            
            if user is not None:
                request.session['user'] = user.user_id
                return redirect('home')
            else:
                form.add_error(None, 'Invalid login')
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'visualnovels/index.html', context=context)

def logout(request):
    del request.session['user']
    return redirect('index')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            request.session['user'] = user.user_id
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'visualnovels/register.html', {'form': form})

def home(request):
    user = User.objects.get(user_id=request.session['user'])
    form = SearchForm(request.GET or None)
    results = []

    if request.GET and form.is_valid():
        results = form.search()

    context = {
        'form': form,
        'results': results,
        'user': user,
    }

    return render(request, 'visualnovels/home.html', context=context)

def visual_novel_detail(request, vn_id):
    vn = get_object_or_404(VisualNovel, vn_id=vn_id)
    user = User.objects.get(user_id=request.session['user'])
    game_list, created = Game_list.objects.get_or_create(user_id=user, vn_id=vn)
    rating, rating_created = Rating.objects.get_or_create(user_id=user, vn_id=vn)
    comment_form = CommentForm(request.POST or None, initial={'vn_id': vn_id, 'user_id': user.user_id})
    comments = Comment.objects.filter(vn_id=vn_id)
    if request.method == 'POST':
        if 'comment_form' in request.POST and comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user_id = user
            comment.vn_id = vn
            comment.save()
            return redirect('visual_novel_detail', vn_id=vn_id) 
        else:
            rating_form = RatingForm(request.POST, instance=rating)
            list_form = GameListForm(request.POST, instance=game_list)
            if rating_form.is_valid() and list_form.is_valid():
                rating_form.save()
                list_form.save()
                return redirect('visual_novel_detail', vn_id=vn_id)
    else:
        rating_form = RatingForm(instance=rating)
        list_form = GameListForm(instance=game_list)
        if rating is None:
            rating_form.fields['rate'].choices = [('choose', 'Choose')] + rating_form.fields['rate'].choices
        if game_list is None:
            list_form.fields['status'].choices = [('choose', 'Choose')] + list_form.fields['status'].choices

    ratings = Rating.objects.filter(vn_id=vn_id)
    genres = vn.genre_set()
    characters = Character.objects.filter(vn_id=vn_id)
    rating_stats = ratings.aggregate(Avg('rate'), Count('rate'))
    rating_counts = [ratings.filter(rate=choice[0]).count() for choice in Rating.RATE_CHOICES]
    
    context = {'vn': vn, 'genres': genres, 'characters': characters, 'user': user, 'ratings': ratings, 'game_list': game_list, 'rating_form': rating_form, 'list_form': list_form, 'comment_form': comment_form, 'comments': comments, 'rating_stats': rating_stats, 'rating_counts': rating_counts}
    return render(request, 'visualnovels/visual_novel_detail.html', context=context)

def visual_novels(request):

    vn_list = VisualNovel.objects.all()
    user = User.objects.get(user_id=request.session['user'])
    status_list = []
    for vn in vn_list:
        status = vn.status_get(user.user_id)
        status_list.append(status)
    super_list = zip(vn_list, status_list)
    context = {'super_list': super_list, 'user': user}
    return render(request, 'visualnovels/visual_novels.html', context=context)

def company_list(request):
    companies = Company.objects.all()
    user = User.objects.get(user_id=request.session['user'])
    context = {'companies': companies, 'user': user}
    return render(request, 'visualnovels/company_list.html', context=context)

def company_detail(request, company_id):
    company = get_object_or_404(Company, company_id=company_id)
    vn_list = company.visualnovel_set.all()
    user = User.objects.get(user_id=request.session['user'])
    context = {'company': company, 'vn_list': vn_list, 'user': user}
    return render(request, 'visualnovels/company_detail.html', context=context)

def character_detail(request, character_id):
    character = get_object_or_404(Character, character_id=character_id)
    user = User.objects.get(user_id=request.session['user'])
    vn = character.vn_id
    context = {
        'character': character,
        'vn': vn,
        'user': user,
    }
    return render(request, 'visualnovels/character_detail.html', context)

def characters(request):
    characters = Character.objects.all()
    user = User.objects.get(user_id=request.session['user'])
    context = {'characters': characters, 'user': user}
    return render(request, 'visualnovels/characters.html', context=context)

def genres(request):
    genres = Genre.objects.all()
    user = User.objects.get(user_id=request.session['user'])
    context = {'genres': genres, 'user': user}
    return render(request, 'visualnovels/genres.html', context=context)

def genre_detail(request, genre_id):
    genre = get_object_or_404(Genre, genre_id=genre_id)
    vn_list = genre.visualnovel_set.all()
    user = User.objects.get(user_id=request.session['user'])
    context = {'genre': genre, 'vn_list': vn_list, 'user': user}
    return render(request, 'visualnovels/genre_detail.html', context=context)

def voice_actors_list(request):
    voice_actors_list = Voice_actor.objects.all()
    user = User.objects.get(user_id=request.session['user'])
    context = {'voice_actors_list': voice_actors_list, 'user': user}
    return render(request, 'visualnovels/voice_actors_list.html', context=context)

def voice_actor_detail(request, va_id):
    voice_actor = get_object_or_404(Voice_actor, va_id=va_id)
    characters = voice_actor.get_characters()
    user = User.objects.get(user_id=request.session['user'])
    context = {'voice_actor': voice_actor, 'characters': characters, 'user': user}
    return render(request, 'visualnovels/voice_actor_detail.html', context=context)

def add_visualnovel(request):
    if request.method == 'POST':
        form = VisualNovelForm(request.POST, request.FILES)
        if form.is_valid():
            novel = form.save(commit=False)
            novel.save()
            form.save_m2m()
            return redirect('visual_novel_detail', vn_id=novel.vn_id)
    else:
        form = VisualNovelForm()
    return render(request, 'visualnovels/add_visual_novel.html', {'form': form})

visualnovels/templates/visualnovels/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>{% block title %}Welcome{% endblock %}</title>
    <style>
      body {
        background-color: black;
    }
    {% block style %}{% endblock %}</style>
  </head>
  <body>
    {% block header %}
    {% endblock %}
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

visualnovels/templates/visualnovels/character_detail.html
{% extends 'visualnovels/base.html' %}

{%block style %}

.border-success,
.border-warning,
.border-primary {
    border: 3px solid;
}
{% endblock %}
{% block header %}
    {% include 'visualnovels/header.html' %}
{% endblock %}

{% block title %}
    {{ character }} - Character Detail
{% endblock %}

{% block content %}
<div class="container p-4" style="background-color: #333;">
    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <img src="https://via.placeholder.com/300x400.png?text=Character+Image" alt="{{ character.first_name }}" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title">{{ character.first_name }} {{ character.last_name }}</h5>
          </div>
        </div>
      </div>
      <div class="col-md-8" style="color: white;">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#overview">Overview</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#novel">Appears in Visual Novels</a>
          </li>
        </ul>
        <div class="tab-content mt-3">
          <div class="tab-pane fade show active" id="overview">
            <p><strong>Age:</strong> {{ character.age }}</p>
            <p><strong>Birth Date:</strong> {{ character.birth_date }}</p>
            <p><strong>Description:</strong> {{ character.description }}</p>
          </div>
          <div class="tab-pane fade" id="novel" style="color: white;">
            <div class="list-group">
              <a href="{% url 'visual_novel_detail' vn.vn_id %}" class="list-group-item list-group-item-action">{{ vn.title }}</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

visualnovels/templates/visualnovels/company_detail.html
{% extends 'visualnovels/base.html' %}

{%block style %}

.border-success,
.border-warning,
.border-primary {
    border: 3px solid;
}
{% endblock %}
{% block header %}
    {% include 'visualnovels/header.html' %}
{% endblock %}

{% block title %}
    {{ company.name }} - Company Detail
{% endblock %}

{% block content %}
<div class="container p-4" style="background-color: #333;">
        <div class="row">
            <div class="col-md-4">
                <img src="https://via.placeholder.com/350x200.png?text={{ company.name }}" alt="{{ company.name }}" class="img-fluid">
            </div>
            <div class="col-md-8">
                <h2 class="text-white">{{ company.name }}</h2>
                <p class="text-white">{{ company.description }}</p>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-md-12">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#visualnovels">Visual Novels</a>
                    </li>
                </ul>
                <div class="tab-content mt-3">
                    <div class="tab-pane fade show active" id="visualnovels">
                        <div class="row">
                            {% for vn in company.visualnovel_set.all %}
                                <div class="col-md-4">
                                    <div class="card mb-4 shadow-sm">
                                        <img src="{{ vn.image.url }}" alt="{{ vn.title }}" class="card-img-top">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ vn.title }}</h5>
                                            <div class="d-flex justify-content-between align-items-center">
                                                <div class="btn-group">
                                                    <a href="{% url 'visual_novel_detail' vn_id=vn.vn_id %}" class="btn btn-sm btn-outline-secondary">View</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% empty %}
                                <p class="text-white">No visual novels found.</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

visualnovels/templates/visualnovels/company_list.html

{% extends 'visualnovels/base.html' %}

{% block title %}Companies{% endblock %}
{%block style %}

.border-success,
.border-warning,
.border-primary {
    border: 3px solid;
}
{% endblock %}
{% block header %}
    {% include 'visualnovels/header.html' %}
{% endblock %}
{% block content %}
<div class="container p-4" style="background-color: #333;">
  <h1 class="mb-3 text-light">Companies</h1>
  <div class="row">
    {% for company in companies %}
    <div class="col-md-4">
      <div class="card mb-4 box-shadow">
        <img class="card-img-top" src="https://via.placeholder.com/350x200.png?text={{ company.name }}" alt="{{ company.name }}">
        <div class="card-body">
          <h5 class="card-title">{{ company.name }}</h5>
          <p class="card-text">{{ company.description }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <a href="{% url 'company_detail' company_id=company.company_id %}" class="btn btn-sm btn-outline-secondary">View</a>
            </div>
            <small class="text-muted">{{ company.visualnovel_set.count }} Visual Novels</small>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

visualnovels/templates/visualnovels/genre_detail.html
{% extends 'visualnovels/base.html' %}

{% block header %}
    {% include 'visualnovels/header.html' %}
{% endblock %}

{% block title %}
    {{ genre.name }} - Genre Detail
{% endblock %}

{% block content %}
<div class="container p-4" style="background-color: #333;">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card mb-3">
          <div class="card-body">
            <h1 class="card-title">{{ genre.name }}</h1>
            <p class="card-text">{{ genre.description }}</p>
            <p class="card-text">Total Visual Novels: {{ vn_list.count }}</p>
          </div>
        </div>
        <div class="row">
          {% for vn in vn_list %}
          <div class="col-md-4">
            <div class="card mb-3">
              <img src="{{ vn.image.url }}" class="card-img-top" alt="{{ vn.title }}">
              <div class="card-body">
                <h5 class="card-title">{{ vn.title }}</h5>
                <a href="{% url 'visual_novel_detail' vn.vn_id %}" class="btn btn-primary">View Details</a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

visualnovels/templates/visualnovels/genres.html
{% extends 'visualnovels/base.html' %}

{% block header %}
    {% include 'visualnovels/header.html' %}
{% endblock %}

{% block title %}Genres{% endblock %}

{% block content %}
<div class="container p-4" style="background-color: #333;">
    <h1 class="mb-3 text-light">Genres</h1>
    <div class="row justify-content-center">
      {% for genre in genres %}
        <div class="col-md-3">
          <div class="card mb-3">
            <div class="card-body">
              <h5 class="card-title">{{ genre.name }}</h5>
              <a href="{% url 'genre_detail' genre.genre_id %}" class="btn btn-primary">View Visual Novels</a>
              <span class="badge badge-info">{{ genre.visualnovel_set.count }} Visual Novels</span>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

visualnovels/templates/visualnovels/visual_novel_detail.html
{% extends 'visualnovels/base.html' %}

{%block style%}

{% endblock %}
{% block title %}
    {{ vn.title }}
{% endblock %}
{% block header %}
  {% include 'visualnovels/header.html' %}
{% endblock %}
{% block content %}
  <div class="container p-4 text-white" style="background-color: #333;">
    <div class="row">
      <div class="col-md-4">
        <img src="{{ vn.image.url }}" alt="{{ vn.title }}" class="img-fluid">
        <div class="dropdown mt-3">
          <div class="dropdown mt-3">
            <form method="post" action="">
              {% csrf_token %}
              {{ rating_form.as_p }}
              {{ list_form.as_p }}
              <button type="submit" class="btn btn-primary">Save</button>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <h2>{{ vn.title }}</h2>
        <p class="lead">{{ vn.description }}</p>
      </div>
    </div>
    <div class="row mt-4">
      <div class="col-md-12">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#overview">Overview</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#company">Company</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#characters">Characters</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#stats">Stats</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#genres">Genres</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#comments">Comments</a>
          </li>
        </ul>
        <div class="tab-content mt-3">
          <div class="tab-pane fade show active" id="overview">
            <h2>{{ vn.title }}</h2>
            <p>{{ vn.description }}</p>
            <ul>
              <li><strong>Released:</strong> {{ vn.released|date:"F j, Y" }}</li>
              <li><strong>Company:</strong> {{ vn.company }}</li>
            </ul>
          </div>
          <div class="tab-pane fade" id="company">
            <div class="row align-items-center">
              <div class="col-12 col-md-8">
                <div class="company-info">
                  <a href="{% url 'company_detail' vn.company.pk %}">
                    <h4>{{ vn.company.name }}</h4>
                  </a>
                  <p>{{ vn.company.description }}</p>
                </div>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="characters">
            <div class="row">
              {% for character in characters %}
              <div class="col-md-4">
                <div class="card mb-4">
                  <img src="https://via.placeholder.com/350x200.png?text=Character+Image" class="card-img-top" alt="{{ character.first_name }} {{ character.last_name }}">
                  <div class="card-body text-dark">
                    <h5 class="card-title">{{ character.first_name }} {{ character.last_name }}</h5>
                    <p class="card-text"><strong>Age:</strong> {{ character.age }}</p>
                    <p class="card-text"><strong>Birth date:</strong> {{ character.birth_date }}</p>
                    <div class="btn-group">
                      <a href="{% url 'character_detail' character.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                  </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          <div class="tab-pane fade" id="stats">
            <p>Stats here</p>
          </div>
          <div class="tab-pane fade" id="genres">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title text-dark">Genres</h3>
              </div>
              <div class="card-body">
                <ul class="list-group">
                  {% for genre in genres %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                      <a href="{% url 'genre_detail' genre.pk %}">{{ genre.name }}</a>
                      <span class="badge badge-primary badge-pill">{{ genre.visualnovel_set.count }}</span>
                    </li>
                  {% empty %}
                    <li class="list-group-item">No genres found.</li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="comments">
            <hr>
            <form method="post" action="">
              {% csrf_token %}
              {{ comment_form.as_p }}
              <button type="submit" name="comment_form" class="btn btn-primary">Add Comment</button>
            </form>
            <hr>
            {% if vn.comment_set.all %}
            <div class="mt-4">
              <h4 class="text-white">Comments</h4>
              {% for comment in vn.comment_set.all %}
              <div class="card border-secondary mb-3">
                <div class="card-header bg-secondary text-white">{{ comment.user_id }}</div>
                <div class="card-body">
                <p class="card-text text-dark">{{ comment.comment }}</p>
                </div>
               </div>
              {% endfor %}
            </div>
            {% else %}
              <p>No comments yet.</p>
            {% endif %}
          </div>
              </div>
            </div>
{% endblock %}